version: "3.1"
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    ports:
      - "11661:8388/tcp"
      - "11661:8388/udp"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=passwd
    restart: always
