version: "3.1"
services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    volumes:
       - pgadmin-data:/var/lib/pgadminn
    ports:
      - "5050:80"
volumes:
  pgadmin-data:
